version: '3.4'
services:  
  otel-collector:
    # using contrib so it includes the loki exporter and service graph exporter
    #image: otel/opentelemetry-collector
    image: otel/opentelemetry-collector-contrib:0.96.0
    hostname: otel-collector
    container_name: otel-collector
    volumes:
      - ./configurations/otel-collector-grafana/otel-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      #- "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
  
  prometheus:
    image: "prom/prometheus"
    hostname: prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configurations/otel-collector-grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    # to passe one flag, such as "--log.level=debug" or "--web.enable-remote-write-receiver", we need to override the whole command, as we can't just pass one extra argument
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # need this for the OpenTelemetry collector to be able to put metrics into Prometheus
      - "--web.enable-remote-write-receiver"
    #   - "--log.level=debug"

  grafana:
    image: "grafana/grafana"
    hostname: grafana
    container_name: grafana
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./configurations/otel-collector-grafana/grafana-provisioning:/etc/grafana/provisioning

  tempo:
    image: grafana/tempo
    hostname: tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configurations/otel-collector-grafana/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo
      #- "4317"  # otlp grpc
      #- "4318"  # otlp http

  loki:
    image: grafana/loki
    hostname: loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./configurations/otel-collector-grafana/loki-config.yaml:/etc/loki/local-config.yaml