version: '3.8'
name: japanese_culture
services:
  rabbitmq:
    container_name: rabbitmqbroker
    hostname: "rabbitmq"
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    container_name: rediscache
    image: "redis:latest"
    ports:
      - "6379:6379"
     
  postgres:
    container_name: pg-database
    image: ankane/pgvector
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    restart: unless-stopped

  pgadmin:
    container_name: pg-database-admin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data: 
