using HotChocolate.Execution.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Manga.GraphQL.Infrastructure;

public static class GraphQlRequestExecutorBuilderExtensions
{
    public static IRequestExecutorBuilder AddMangaGraphql(this IRequestExecutorBuilder builder)
    {
        // Autogenerated extension
        builder.AddMangaGraphqlTypes();
        return builder;
    }
}