receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  attributes/PII-data-cleanup:
    actions:
      - key: sureName
        action: delete
  attributes/environment-setup:
    actions:
      - key: environment
        value: development
        action: upsert
  tail_sampling:
    decision_wait: 5s
    # Evaluates the following policies in case any match we sample the traces
    policies:
      [
        {
          # Rule: low sampling for readiness/liveness probes from dotnet-api
          name: sample-partial-health-probes,
          type: and,
          and:
            {
              and_sub_policy:
                [
                  {
                    # filter by service name
                    name: service-name-policy,
                    type: string_attribute,
                    string_attribute:
                      {
                        key: service.name,
                        values: [ dotnet-api ],
                      },
                  },
                  {
                    # filter by route
                    name: route-live-ready-policy,
                    type: string_attribute,
                    string_attribute:
                      {
                        key: http.route,
                        values: [ /live, /ready, /healthcheck ],
                        enabled_regex_matching: true,
                      },
                  },
                  {
                    # apply probabilistic sampling
                    name: probabilistic-policy,
                    type: probabilistic,
                    probabilistic: { sampling_percentage: 0.1 },
                  },
                ],
            },
        },
        {
          # Rule: Sample all errors from dotnet-api
          name: sample-all-errors,
          type: and,
          and:
            {
              and_sub_policy:
                [
                  {
                    # filter by service name
                    name: service-name-policy,
                    type: string_attribute,
                    string_attribute:
                      {
                        key: service.name,
                        values: [ dotnet-api ],
                      },
                  },
                  {
                    name: error-check-policy,
                    type: status_code,
                    status_code: { status_codes: [ ERROR ] }
                  }
                ]
            }
        },
        {
          # Rule: low sampling for hangfire probes from dotnet-api 
          name: sample-partial-hangfire-probes,
          type: and,
          and:
            {
              and_sub_policy:
                [
                  {
                    name: service-name-policy,
                    type: string_attribute,
                    string_attribute:
                      {
                        key: service.name,
                        values: [ dotnet-api ],
                      },
                  },
                  {
                    name: check-db-command-policy,
                    type: string_attribute,
                    string_attribute: { key: db.statement, values: [ ".*hangfire.*" ], enabled_regex_matching: true, cache_max_size: 10 }
                  },
                  {
                    name: probabilistic-policy,
                    type: probabilistic,
                    probabilistic: { sampling_percentage: 0.1 },
                  },
                ]
            }
        },
        {
          name: sample-long-running-requests,
          type: latency,
          latency: { threshold_ms: 100 }
        }
      ]


exporters:
  debug:
    verbosity: detailed
  otlp/aspire:
    endpoint: ${env:ASPIRE_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/aspire ]
    traces:
      receivers: [ otlp ]
      processors:
        - batch
#        - attributes/environment-setup
#        - attributes/PII-data-cleanup
#        - tail_sampling
      exporters:
        - otlp/aspire
        - debug
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - otlp/aspire