name: Dockerize japanese.api
on:
  push:

jobs:
  build:
    name: Dockerize japanese.api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: just a simple ls command
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/japanese-api
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} -f src/host/Japanese.Api/Dockerfile .
          docker push --all-tags $IMAGE_NAME

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: "./src/host/japanese.api/Dockerfile"
          tags: japanese/app:latest