name: Dockerize rating.api
on:
  push:

jobs:
  build:
    name: Dockerize rating.api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./dockerfiles/rating-api/Dockerfile
          push: true
          tags: razorscream/cultural-rating-api:${{ steps.version_step.outputs.MajorMinorPatch }}.${{ steps.version_step.outputs.PreReleaseLabel }}.${{ steps.version_step.outputs.CommitsSinceVersionSource }}